
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

RUN apt update
RUN apt install -y python3-pip  python3-edgetpu \ 
			edgetpu-examples libedgetpu1-legacy-std 


WORKDIR /app

COPY run.sh run.sh

CMD ["bash","run.sh"]
